###########
# site.title

title:    'Tyler Spear / UX Designer'
subtitle: 'A potrolio site dedicated to UX Design'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md

sass:
  style: compact # possible values: nested expanded compact compressed

sass:
    sass_dir: _sass
