###########
# site.title

title:    'Jekyll Starter Theme'
subtitle: 'Another Minimalistic Static Site Quick Starter Theme'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md

sass:
  style: compact # possible values: nested expanded compact compressed

sass:
    sass_dir: _sass
